//---------------------------------------------------------------------------

#ifndef Unit1H
#define Unit1H
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ExtCtrls.hpp>
#include <Graphics.hpp>
#include <Buttons.hpp>
#include <ComCtrls.hpp>
#include <ImgList.hpp>
//---------------------------------------------------------------------------
class TMonopoly : public TForm
{
__published:	// IDE-managed Components
        TBitBtn *StartGameButton;
        TImage *Image1;
        TImage *Image2;
        TImage *Image3;
        TImage *Image4;
        TImage *Image5;
        TImage *Image6;
        TImage *Image7;
        TImage *Image8;
        TImage *Image9;
        TImage *Image10;
        TImage *Image11;
        TImage *Image12;
        TImage *Image13;
        TImage *Image20;
        TImage *Image16;
        TImage *Image21;
        TImage *Image23;
        TImage *Image24;
        TImage *Image25;
        TImage *Image26;
        TImage *Image27;
        TImage *Image39;
        TImage *Image30;
        TImage *Image22;
        TImage *Image14;
        TImage *Image17;
        TImage *Image28;
        TImage *Image29;
        TImage *Image18;
        TImage *Image31;
        TImage *Image32;
        TImage *Image33;
        TImage *Image34;
        TImage *Image35;
        TImage *Image36;
        TImage *Image37;
        TImage *Image38;
        TImage *Image15;
        TImage *Image19;
        TImage *Image40;
        TEdit *Edit1;
        TBitBtn *SendMessageButton;
        TBitBtn *AddPlayer1;
        TPanel *Player1;
        TImage *Image41;
        TEdit *Player1Nickname;
        TBitBtn *Player1Ready;
        TLabel *Player1Name;
        TBitBtn *AddPlayer2;
        TBitBtn *AddPlayer3;
        TBitBtn *AddPlayer4;
        TPanel *Player2;
        TPanel *Player3;
        TPanel *Player4;
        TImage *Image42;
        TBitBtn *Player2Ready;
        TLabel *Label2;
        TLabel *Player2Name;
        TEdit *Player2Nickname;
        TImage *Image43;
        TBitBtn *Player3Ready;
        TEdit *Player3Nickname;
        TLabel *Player3Name;
        TImage *Image44;
        TBitBtn *Player4Ready;
        TEdit *Player4Nickname;
        TLabel *Player4Name;
        TLabel *Player1Money;
        TLabel *Player2Money;
        TLabel *Player3Money;
        TLabel *Player4Money;
        TMemo *Chat;
        TBitBtn *BitBtn1;
        TGroupBox *GroupBox1;
        TLabel *Label1;
        TBitBtn *BitBtn2;
        TShape *Player1Shape;
        TShape *Player2Shape;
        TShape *Player3Shape;
        TShape *Player4Shape;
        TPanel *Panel1;
        TPanel *Panel3;
        TPanel *Panel5;
        TPanel *Panel6;
        TPanel *Panel8;
        TPanel *Panel9;
        TPanel *Panel21;
        TPanel *Panel23;
        TPanel *Panel24;
        TPanel *Panel25;
        TPanel *Panel26;
        TPanel *Panel27;
        TPanel *Panel29;
        TPanel *Panel28;
        TPanel *LeftCoubPanel;
        TImage *Coub1;
        TImage *Coub2;
        TPanel *RightCoubPanel;
        TTimer *Timer1;
        TPanel *Panel11;
        TPanel *Panel12;
        TPanel *Panel13;
        TPanel *Panel14;
        TPanel *Panel15;
        TPanel *Panel16;
        TPanel *Panel31;
        TPanel *Panel18;
        TPanel *Panel19;
        TPanel *Panel39;
        TPanel *Panel37;
        TPanel *Panel35;
        TPanel *Panel34;
        TPanel *Panel32;
        TGroupBox *GroupBox2;
        TBitBtn *BitBtn3;
        TBitBtn *BitBtn4;
        TShape *Shape1;
        TShape *Shape2;
        TShape *Shape3;
        TShape *Shape4;
        TShape *Shape5;
        TShape *Shape6;
        TShape *Shape7;
        TShape *Shape8;
        TShape *Shape9;
        TShape *Shape10;
        TShape *Shape11;
        TShape *Shape12;
        TShape *Shape13;
        TShape *Shape14;
        TShape *Shape15;
        TShape *Shape16;
        TShape *Shape17;
        TShape *Shape18;
        TShape *Shape19;
        TShape *Shape20;
        TShape *Shape21;
        TShape *Shape22;
        TShape *Shape23;
        TShape *Shape24;
        TShape *Shape25;
        TShape *Shape26;
        TShape *Shape27;
        TShape *Shape28;
        TShape *Shape29;
        TShape *Shape30;
        TShape *Shape31;
        TShape *Shape37;
        TShape *Shape38;
        TShape *Shape39;
        TShape *Shape40;
        TShape *Shape41;
        TShape *Shape42;
        TShape *Shape43;
        TShape *Shape44;
        TShape *Shape45;
        TShape *Shape46;
        TShape *Shape47;
        TShape *Shape48;
        TShape *Shape49;
        TShape *Shape50;
        TShape *Shape51;
        TShape *Shape52;
        TShape *Shape53;
        TShape *Shape54;
        TShape *Shape55;
        TShape *Shape56;
        TShape *Shape57;
        TShape *Shape58;
        TShape *Shape59;
        TShape *Shape60;
        TShape *Shape61;
        TShape *Shape62;
        TShape *Shape63;
        TShape *Shape64;
        TShape *Shape65;
        TShape *Shape66;
        TShape *Shape67;
        TShape *Shape68;
        TShape *Shape69;
        TShape *Shape70;
        TShape *Shape71;
        TShape *Shape72;
        TShape *Shape77;
        TShape *Shape78;
        TShape *Shape79;
        TShape *Shape80;
        TShape *Shape81;
        TShape *Shape82;
        TShape *Shape83;
        TShape *Shape84;
        TShape *Shape85;
        TShape *Shape86;
        TShape *Shape87;
        TShape *Shape88;
        TShape *Shape89;
        TShape *Shape90;
        TShape *Shape91;
        TShape *Shape92;
        TShape *Shape93;
        TShape *Shape94;
        TShape *Shape95;
        TShape *Shape96;
        TShape *Shape32;
        TShape *Shape97;
        TPanel *DeletePlayer1;
        TPanel *Panel2;
        TPanel *DeletePlayer3;
        TPanel *Panel4;
        TBitBtn *BitBtn5;
        TBitBtn *BitBtn6;
        TBitBtn *BitBtn7;
        TBitBtn *BitBtn8;
        TLabel *Label3;
        TGroupBox *GroupBox3;
        TBitBtn *BitBtn9;
        TBitBtn *BitBtn10;
        TRadioButton *RadioButton1;
        TRadioButton *RadioButton2;
        TRadioButton *RadioButton3;
        TRadioButton *RadioButton4;
        TRadioButton *RadioButton5;
        TRadioButton *RadioButton6;
        void __fastcall StartGameButtonClick(TObject *Sender);
        void __fastcall FormCreate(TObject *Sender);
        void __fastcall AddPlayer1Click(TObject *Sender);
        void __fastcall Player1ReadyClick(TObject *Sender);
        void __fastcall Player2ReadyClick(TObject *Sender);
        void __fastcall Player3ReadyClick(TObject *Sender);
        void __fastcall Player4ReadyClick(TObject *Sender);
        void __fastcall BitBtn2Click(TObject *Sender);
        void __fastcall BitBtn1Click(TObject *Sender);
        void __fastcall SendMessageButtonClick(TObject *Sender);
        void __fastcall Timer1Timer(TObject *Sender);
        void __fastcall BitBtn3Click(TObject *Sender);
        void __fastcall BitBtn4Click(TObject *Sender);
        void __fastcall Player2Click(TObject *Sender);
        void __fastcall Player1Click(TObject *Sender);
        void __fastcall Player3Click(TObject *Sender);
        void __fastcall Player4Click(TObject *Sender);
        void __fastcall FormClick(TObject *Sender);
        void __fastcall BitBtn5Click(TObject *Sender);
        void __fastcall BitBtn6Click(TObject *Sender);
        void __fastcall BitBtn7Click(TObject *Sender);
        void __fastcall BitBtn8Click(TObject *Sender);
        void __fastcall BitBtn9Click(TObject *Sender);
        void __fastcall BitBtn10Click(TObject *Sender);
private:	// User declarations
public:		// User declarations
        __fastcall TMonopoly(TComponent* Owner);
};
//---------------------------------------------------------------------------
extern PACKAGE TMonopoly *Monopoly;
//---------------------------------------------------------------------------
#endif
 